SELECT * FROM WORKER;
SELECT SALARY FROM WORKER;
SELECT FIRST_NAME, SALARY FROM WORKER;
SELECT 44+33;
SELECT NOW();
SELECT UCASE('tushaR');
SELECT * FROM Worker WHERE SALARY>100000;

-- SALARY [80000, 300000]
SELECT * FROM Worker WHERE SALARY BETWEEN 80000 AND 300000;

-- REDUCE OR STATEMENTS use IN 
-- HR ADMIN
SELECT * FROM Worker WHERE DEPARTMENT = 'HR' OR DEPARTMENT = 'Admin';
SELECT * FROM Worker WHERE DEPARTMENT IN ('HR','Admin');

-- NOT IN
SELECT * FROM Worker WHERE DEPARTMENT NOT IN ('HR','Admin');

-- IS NULL
SELECT * FROM Worker WHERE DEPARTMENT IS NULL; 

-- WILDCARD
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%K_';
SELECT * FROM Worker WHERE FIRST_NAME LIKE '%I%';
SELECT * FROM Worker WHERE FIRST_NAME LIKE '_i%';

-- SORTING USINNG ORDER BY DEFAULT ASC 
SELECT * FROM Worker ORDER BY SALARY; 
SELECT * FROM Worker ORDER BY SALARY DESC; 
SELECT * FROM Worker ORDER BY SALARY ASC;

-- DISTINCT
SELECT DISTINCT  DEPARTMENT FROM Worker;

-- Q.find no. of employee working in different department 
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM Worker GROUP BY DEPARTMENT;

-- Q.FIND AVG SALARY PER DEPARTMENT
SELECT DEPARTMENT, AVG(SALARY) FROM Worker GROUP BY DEPARTMENT;

-- Q. FIND MIN SALARY PER DEPARTMENT
SELECT DEPARTMENT, MIN(SALARY) FROM Worker GROUP BY DEPARTMENT;

-- Q. FIND MAX SALARY PER DEPARTMENT
SELECT DEPARTMENT, MAX(SALARY) FROM Worker GROUP BY DEPARTMENT;

-- Q. FIND SUM SALARY PER DEPARTMENT
SELECT DEPARTMENT, SUM(SALARY) FROM WORKER GROUP BY DEPARTMENT;

-- Q. DEPARTMENT COUNT HAVING MORE THAN 2 WORKERS?
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)>2;

