-- SUB QUERIES
-- WHERE CLAUSE SAME TABLE
-- employees with age>30
SELECT * FROM EMPLOYEE WHERE age>30;

SELECT * FROM EMPLOYEE WHERE age IN 
(SELECT age FROM EMPLOYEE WHERE age>30);

-- WHERE CLAUSE DIFFERENT TABLE
-- emp details working in more than 1 project
SELECT * FROM EMPLOYEE WHERE ID IN 
(SELECT EMPID FROM PROJECT GROUP BY EMPID HAVING COUNT(EMPID)>1);

-- SINGLE VALUE SUBQUERY
-- employees with age>AVG(AGE)
SELECT * FROM EMPLOYEE WHERE age >
(SELECT AVG(age) FROM EMPLOYEE);

-- FROM CLAUSE
-- SELECT MAX AGE PERSON WHOSE FIRST NAME HAS 'a'
SELECT max(age) FROM EMPLOYEE where fname LIKE '%a%'; 

SELECT MAX(age) FROM (SELECT * FROM EMPLOYEE WHERE fname LIKE '%a%') AS TEMP;

-- CORELATED SUBQUERY
-- FIND 3RD OLDEST EMPLOYEE
SELECT * FROM EMPLOYEE AS E1 WHERE 2 IN
(SELECT COUNT(*) FROM EMPLOYEE AS E2 WHERE E2.AGE>E1.AGE);

-- creating a view 
CREATE VIEW custom_view AS SELECT fname, age FROM EMPLOYEE;

-- VIEWING THE VIEW
SELECT * FROM custom_view;

-- ALTERING THE VIEW
ALTER VIEW custom_view AS SELECT fname, lname, age FROM EMPLOYEE;

-- DROPING THE VIEW
DROP VIEW IF EXISTS custom_view;